config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index'

  get     '/sign_up'  => 'clearance/users#new',         as: :sign_up
  get     '/sign_in'  => 'clearance/sessions#new',      as: :sign_in
  delete  '/sign_out' => 'clearance/sessions#destroy',  as: :sign_out

  resource  :session,   controller: 'clearance/sessions',  only: :create
  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resources :users,     controller: 'users',               only: :create do
    resource :password, controller: 'clearance/passwords', only: [:create, :edit, :update]
  end

  resources :lists, only: [:new, :create] do
    resources :tasks, controller: 'lists/tasks', only: [:new, :create, :update] do
      member do
        post :assign
      end
    end

    member do
      post :archive
    end
  end

  post '/search' => 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates :user_id, presence: true
  validates :task_id, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  STATUSES = %w(active archived)

  has_many :tasks, dependent: :destroy

  enum status:  [:active, :archived]

  validates :status, presence: true, inclusion: { in: STATUSES }
  validates :name,   presence: true, length: { maximum: 100 }

  scope :without,           -> (id)    { where.not(id: id) }
  scope :with_task_like,    -> (query) { eager_load(:tasks).where("tasks.title iLIKE '%#{query}%'") }
  scope :active_search_for, -> (query) { with_task_like(query).active }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  has_many   :assignments
  has_many   :users, through: :assignments, dependent: :destroy

  validates :title,       presence: true
  validates :description, presence: true
  validates :list_id,     presence: true

  scope :like, -> (query) { joins(:list).merge(List.active).where("title iLIKE '%#{query}%'") }
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  PASSWORD_REGEX = /(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/

  has_many :assignments
  has_many :tasks, through: :assignments, dependent: :destroy

  validates :name,      presence: true
  validates :email,     presence: true
  validates :password,  unless: :skip_password_validation?,
                        format: {
                          with: PASSWORD_REGEX,
                          message: "must include at least one lowercase letter, one uppercase letter, and one digit"
                        }

  scope :without_assignment_for, -> (task) { where.not(id: task.users.map{|s|s.id}) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_login

  expose(:facade) { DashboardFacade.new(request) }

  def index
  end
end

app/controllers/lists/tasks_controller.rb
class Lists::TasksController < ApplicationController
  before_action :require_login

  expose(:facade) { Lists::TasksFacade.new(request) }

  def new
    @task ||= facade.list.tasks.build
  end

  def create
    result = facade.create_service.call

    if result.success?
      redirect_to(root_path, flash: { success: "Task created" })
    else
      @task = result.data.task
      flash[:error] = @task.errors.to_a.join(". ")
      render(:new)
    end
  end

  def update
    result = facade.update_service.call
    flash = result.success? ? { success: "Task updated" } : { error: result.data.task.errors.to_a.join(". ") }
    redirect_to(root_path, flash: flash)
  end

  def assign
    result = facade.assign_service.call
    redirect_to(root_path, flash: { success: "Task assigned" })
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :require_login

  expose(:facade) { ListsFacade.new(request) }

  def new
    @list ||= List.new
  end

  def create
    result = facade.create_service.call

    if result.success?
      redirect_to(root_path, flash: { success: "List created" })
    else
      @list = result.data.list
      flash[:error] = @list.errors.to_a.join(". ")
      render(:new)
    end
  end

  def archive
    facade.list.archived!
    redirect_to(root_path, flash: { success: "List archived" })
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def create
    super.tap do |block|
      flash[:error] = @user.errors.to_a.join(". ") if @user.errors.any?
    end
  end

  private

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    name = user_params.delete(:name)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.name = name
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.haml
#dashboard.row
  .col-12.col-sm-12
    #lists
      = render "lists/collection"

app/views/dashboard/index.js.erb
$("#lists").html("<%= escape_javascript(render(partial: "lists/collection")) %>");

$("li.task").each(function() {
  return $(this).taskHandler();
});

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Trellish
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      %nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
        = link_to "Trellish", root_path, class: "navbar-brand"  
        %button.navbar-toggler.collapsed{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", data: {target: "#navbarCollapse", toggle: "collapse"}, type: "button"}
          %span.navbar-toggler-icon
        #navbarCollapse.navbar-collapse.collapse
          - if current_user
            %ul.navbar-nav.mr-auto
              %li.nav-item
                = link_to "New list", new_list_path, class: "nav-link"
              %li.nav-item
                = link_to "Logout", sign_out_path, method: :delete, class: "nav-link"
            = form_tag search_path, method: :post, remote: true, class: "form-inline mt-2 mt-md-0" do
              = hidden_field_tag :authenticity_token, form_authenticity_token
              = text_field_tag :task_filter, nil, placeholder: "Search", class: "form-control mr-sm-2"
    #flashes{class: flash.any? ? '' : 'hide'}
      - flash.each do |type, message|
        %div{class: "flash flash-static flash-#{type} #{type == 'error' ? 'bg-danger' : 'bg-success'}"}
          = message
          %button.close{"aria-label" => "Close", data: {dismiss: "alert"}, type: "button"}
            %span= "&#10005;".html_safe
    %main.container-fluid
      = yield
    %footer.footer
      .container
        %span.text-muted= "Trellish &copy; #{Time.now.year}".html_safe

app/views/lists/_collection.html.haml
- if facade.lists.any?
  - facade.lists.each do |list|
    .card.list{data: {id: list.id}}
      .card-header
        = list.name.upcase
        %br
        = link_to "Add task", new_list_task_path(list), class: "badge badge-primary"
        = link_to "Archive", archive_list_path(list), method: :post, data: {confirm: "Are you sure you want to archive \"#{list.name.upcase}\"?"}, class: "badge badge-danger"
      %ul.list-group.list-group-flush.tasks
        - if list.tasks.any?
          - list.tasks.each_with_index do |task, i|
            %li.list-group-item{class: ["task", (i.even? ? "even" : "odd")], data: {id: task.id}}
              %h5= task.title
              %p= task.description
              - if task.users.any?
                %p
                  .small Assignees:
                  - task.users.each do |user|
                    %span.badge.badge-secondary= user.name
              %hr
              - if facade.assignable_users_for(task).any?
                = form_for :task, url: assign_list_task_path(list, task), method: :post do |f|
                  = f.select :user_id, options_for_select(facade.assignable_users_for(task).collect{|u| [u.name, u.id]}), {include_blank: "Assign..."}, class: "assignee-input form-control form-control-sm"
              = form_for task, url: list_task_path(list, task), method: :put do |f|
                = f.select :list_id, options_for_select(facade.all_lists_but(list).collect{|l| [l.name, l.id]}), {include_blank: "Move to..."}, class: "list-input form-control form-control-sm"
        - else
          .card-body No tasks yet
- else
  %p.lead Sorry, no lists here. Add new one above or search again. 

app/views/lists/new.html.haml
%h1.heading.text-center Create new list
#new-list.row
  .col-12.col-sm-8.offset-sm-2.col-md-6.offset-md-3.col-lg-4.offset-lg-4
    = form_for @list do |f|
      = f.text_field :name, placeholder: "Name", class: "name-input form-control"
      = f.submit "Create", class: "btn btn-primary btn-block btn-submit"

app/views/lists/tasks/new.html.haml
%h1.heading.text-center 
  Create new task for
  .text-primary= facade.list.name.upcase
#new-task.row
  .col-12.col-sm-8.offset-sm-2.col-md-6.offset-md-3.col-lg-4.offset-lg-4
    = form_for @task, url: list_tasks_path(list_id: facade.list.id) do |f|
      = f.text_field :title, placeholder: "Title", class: "title-input form-control"
      = f.text_area :description, placeholder: "Describe your task here...", class: "description-input form-control"
      = f.submit "Create", class: "btn btn-primary btn-block btn-submit"

app/views/users/new.html.haml
%h1.heading.text-center Sign up
#sign-up.row
  .col-12.col-sm-8.offset-sm-2.col-md-6.offset-md-3.col-lg-4.offset-lg-4
    = form_for @user do |f|
      = f.text_field :name, placeholder: "Name", class: "name-input form-control"
      = f.text_field :email, type: 'email', placeholder: "Email", class: "email-input form-control"
      = f.password_field :password, placeholder: "Password", class: "password-input form-control"
      = f.submit "Sign up", class: "btn btn-primary btn-block"
      = link_to "Have an account? Sign in!", sign_in_path, class: "btn btn-sm btn-info btn-block"